configurations:
  Control_list: 
    - "glandular cells"
    - "glandular cells"
    - "glandular cells"
    - "alveolar cells" 
  Normal_tissue_list:
    - "breast"
    - "prostate"
    - "colon"
    - "lung" 
  Cancer_list:
    - "breast cancer"
    - "prostate cancer"
    - "colorectal cancer"
    - "lung cancer" 
  plot_bar: True 
  dimension_list:
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
  max_iter: 1000
  Annotation: "Leaf"
  optimal_dim: 200
  network_access_wrapper: 
    "{script}"
  # this option exists for the sake of preparing a network connection on clusters with controlled access.
  # it must be written in linux shell script and contain "{script}",
  # which will be replaced by the command that starts the network dependent process
  # optional fields are {log} (replaced by the absolute path of the log file) and 
  # {workdir} (replaced by the absolute path of the working directory).
  # "conda run -p '$CONDA_PREFIX' {script};" is required if a change of environment took place.
  NCBI_account: "" 
  # email of NCBI account to be used
